server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 配置日志
    #access_log  /var/log/nginx/host-access.log main;
    error_log /var/log/nginx/host-error.log warn;

    # 前端路径
    location / {
        root   /var/www/html;
        index  index.html index.htm;
        # 支持路由
        try_files $uri $uri/ /index.html; 
        # 跨域
        add_header Access-Control-Allow-Origin '*';
        if ($request_filename ~* .*\.(?:htm|html)$) {
          add_header Access-Control-Allow-Origin '*';
          add_header Cache-Control "no-cache, no-store";
        }
    }

    # 启用压缩
    gzip on;
    gzip_min_length  1k;
    gzip_buffers 4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 9;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png application/vnd.ms-fontobject font/ttf font/opentype font/x-woff image/svg+xml;
    
}